sonar.projectKey=tn.enicar:enicar-connect
sonar.projectName=ENICAR Connect
sonar.java.binaries=target/classes
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
# Exclude DTOs and Configs from severe threshold calculations
sonar.coverage.exclusions=**/dto/**,**/config/**,**/*Application.java