const fs = require('fs');
const path = require('path');
const base = 'src/app/features/groups';
const target = '../../../core/services/group.service';
const resolved = path.resolve(base, target) + '.ts';
console.log('Resolved path:', resolved);
console.log('Exists:', fs.existsSync(resolved));
const base2 = 'src/app/features/groups';
const target2 = '../../../shared/navbar/navbar.component';
const resolved2 = path.resolve(base2, target2) + '.ts';
console.log('Resolved navbar:', resolved2);
console.log('Exists:', fs.existsSync(resolved2));
